# Generated by Django 2.1.4 on 2018-12-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawDialog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_text', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'raw_dialog',
            },
        ),
    ]
