# Generated by Django 2.1.4 on 2018-12-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensoredDialog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_text', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'censored_dialogs',
            },
        ),
        migrations.AlterModelTable(
            name='rawdialog',
            table='raw_dialogs',
        ),
        migrations.AddField(
            model_name='censoreddialog',
            name='raw_dialog',
            field=models.ForeignKey(db_column='raw_dialog_id', on_delete=django.db.models.deletion.CASCADE, related_name='censored_dialogs', to='censor_app.RawDialog'),
        ),
    ]
